### ISSUE TITLE
Support Ghidra 9.1-BETA_DEV

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Maschell/GhidraRPXLoader#3]
The plugin does not work for [`Ghidra 9.1-BETA_DEV`](https://ghidra-sre.org/ghidra_9.1-BETA_DEV_20190923.zip).

Maybe only a recompilation is required.

The last supported version is [`Ghidra 9.0.4 PUBLIC`](https://ghidra-sre.org/ghidra_9.0.4_PUBLIC_20190516.zip).

**Comment by exjam** [comment]
This should be fixed now
