### ISSUE TITLE
Going to external location does not (always) work

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Maschell/GhidraRPXLoader#6]
If you try to follow an import into another `RPL` via the `Symbol Tree` `Imports` -> `*.rpl` -> `Function name` -> `Go to External Location`, it will not take you to the correct location.

For example load `vpad.rpl` and try to follow `OSGetForegroundBucket` from `coreinit.rpl`.

**Comment by Maschell** [comment]
Fixed with commit 0005907
